### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by akshay1027** [fave77/pbchess#102]
**Is your feature request related to a problem? Please describe.** :bulb:
1)Find us
2)Call us
3)Mail us
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

**Comment by akshay1027** [comment]
I would like to work on this @fave77

**Comment by fave77** [comment]
@akshay1027 this is a very generic template and the whole site is supposed to be minimalistic... hence, closing it.
