### ISSUE TITLE
Spacial arrangements and adding Icons to the Content in navbar

### ISSUE THREAD

**Issue by anhushree** [fave77/pbchess#109]
**Describe the bug** :bug:
Contents in the navbar on the homepage are not arranged spacially 

**Expected behavior** :honeybee:
Space between  Play Learn Login can be increased, The UI design of the navbar can be improved (can include icons for it to look visually pleasing). 

**Screenshots** :camera:
![image](https://user-images.githubusercontent.com/56672958/114336364-6351a380-9b6c-11eb-97db-e4ad50f9bbf2.png)

**Comment by fave77** [comment]
@anhushree Can you provide a mockup first as to how you can improve it?

**Comment by anhushree** [comment]
Yes sure will do it in Figma and send you the link. @fave77

**Comment by fave77** [comment]
> Yes sure will do it in Figma and send you the link. @fave77

@anhushree okay

**Comment by anhushree** [comment]
https://www.figma.com/file/RLd2OE2errq9WcjxdB4t9d/pbchess?node-id=0%3A1
@fave77 Kindly check this. Let me know if there is any modification

**Comment by fave77** [comment]
@anhushree I prefer the Desktop-2 design! However, do not add spaces before the logo or the end of the login, just in between play and learn, learn and login.

As for icons, you can experiment with different variants, like with diff color or theme color.
Let me know your discord username for GSSoC'21, and then will assign you this issue!

**Comment by anhushree** [comment]
https://www.figma.com/file/RLd2OE2errq9WcjxdB4t9d/pbchess?node-id=0%3A1 
Kindly check the Desktop-2 Artboard, I have made the respective changes.

Image:
![image](https://user-images.githubusercontent.com/56672958/114502155-f233ee00-9c48-11eb-9275-8ded4e09cf0d.png)

**Comment by anhushree** [comment]
Discord Username: Anhushree (P)#5454

**Comment by anhushree** [comment]
> @anhushree I prefer the Desktop-2 design! However, do not add spaces before the logo or the end of the login, just in between play and learn, learn and login.
> 
> As for icons, you can experiment with different variants, like with diff color or theme color.
> Let me know your discord username for GSSoC'21, and then will assign you this issue!

sure will do it !!!

**Comment by fave77** [comment]
> https://www.figma.com/file/RLd2OE2errq9WcjxdB4t9d/pbchess?node-id=0%3A1
> Kindly check the Desktop-2 Artboard, I have made the respective changes.
> 
> Image:
> ![image](https://user-images.githubusercontent.com/56672958/114502155-f233ee00-9c48-11eb-9275-8ded4e09cf0d.png)

Do not change the position of the logo and login from the current [site](https://develop.pbchess.cf)
