### ISSUE TITLE
Making a editable user profile page

### ISSUE THREAD

**Issue by sorbx64** [fave77/pbchess#11]
**Is your feature request related to a problem? Please describe.** :bulb:
No.

**Describe the solution you'd like** :sparkles:
A profile page for the user's information. It should contain:
1. A profile image for the user (editable)
1. Username (unedtiable)
1. When user Joined (uneditable)
1. Fullname (editable)
1. Email address (editable)
1. Gender (editable)
1. Country (editable)
1. An <i>Edit Profile</i> button and following that a <i>View Games</i> button.

Profile page should look as below in additional context.

On pressing the edit profile button a popup fullscreen edit modal should appear for filling the new details that will replace the old ones. And it should be as below in additional context.

**Describe alternatives you've considered** :star2:
N/A

**Additional context** :memo:
- Edit profile button should only appear for user that is related to the profile, for other users edit profile button should not appear.

<i>Mockups</i>

Profile page
<img src="https://user-images.githubusercontent.com/60147716/104364788-1b0af100-553d-11eb-9ffd-70816adc56e6.png" width="250px">

Profile Page Edit Modal
<img src="https://user-images.githubusercontent.com/60147716/104365346-e5b2d300-553d-11eb-8bdd-c2c5b2c17c03.png" width="250px">

**Comment by magjoy6** [comment]
I want to fix this issue with the help of bootstrap.. could you assign me for this work?

**Comment by fave77** [comment]
@magjoy6 are you a JWoC participant?

**Comment by fave77** [comment]
@magjoy6 are you a JWoC participant?

**Comment by magjoy6** [comment]
@fave77 yes I am

**Comment by fave77** [comment]
@magjoy6 I apologize for the inconvenience, but this issue is not under JWoC and already assigned to @saurabh-33. Please find any other issues to work on or raise new ones if you find any bugs or have an idea about a new feature. Do discuss beforehand on our discord channel.
