### ISSUE TITLE
Adding Close button for Login/SignUp page

### ISSUE THREAD

**Issue by anhushree** [fave77/pbchess#110]
**Describe the bug** :bug:
The User accidentally clicks on Login, but wants to Learn first, he finds no back or close button. Hence adding a close button `X` on the top of the Login/SignUp page will improve the User Experience 

**Expected behavior** :honeybee:
The Login/SignUp pages close, on clicking the `X` button.

**Screenshots** :camera:
![image](https://user-images.githubusercontent.com/56672958/114337125-28e90600-9b6e-11eb-9e54-e1fc4ad7eca3.png)
![image](https://user-images.githubusercontent.com/56672958/114337142-2edee700-9b6e-11eb-9312-4be8fa98d1d3.png)

**Comment by fave77** [comment]
@anhushree An user can always click the `Learn` tab on the navbar!
