### ISSUE TITLE
Chess Openings

### ISSUE THREAD

**Issue by rahulrj1** [fave77/pbchess#111]
**Is your feature request related to a problem? Please describe.** :bulb:
I would like to add a section to pbchess learn for famous chess openings.

**Describe the solution you'd like** :sparkles:
I would like to write about some famous chess openings like Sicilian Defense, King's Gambit, Ruy Lopez, Danish Gambit and so on along with proper images and ideas behind these openings.

**Comment by fave77** [comment]
@rahulrj1 Would you be interested in writing an article namely, `chess_openings.md`?
 For more details on the write-up format, please refer to the issue #25

**Comment by rahulrj1** [comment]
yes, I am interested.

**Comment by rahulrj1** [comment]
@fave77 Am I allowed to make a folder "Images" in .github/lessons/ to put the relevant images or is there any another particular location where I should put the images?

**Comment by fave77** [comment]
@rahulrj1 no need to create a folder, you can host the image on GitHub itself, check [here](https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d)
