### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by MennaMagdy2019** [fave77/pbchess#114]
**Is your feature request related to a problem? Please describe.** :bulb:

**Describe the solution you'd like** :sparkles:
I will make a vertical scrollbar

**Describe alternatives you've considered** :star2:
I will make a vertical scrollbar as the color of the navbar, border-radius, and Box-shadow to this scrollBar

![Capture12](https://user-images.githubusercontent.com/50016070/114456964-c6c7e980-9bdd-11eb-9b8f-13e2bdee6428.JPG)
 think it will look nice. Can you assign me this issue please @fave77, thank you

**Comment by fave77** [comment]
@MennaMagdy2019 please provide a mock-up first

**Comment by MennaMagdy2019** [comment]
before hover on the scrollbar
It will be
![befor1](https://user-images.githubusercontent.com/50016070/114499744-0a931100-9c27-11eb-8769-f0af29fd9bcd.JPG)

and after hover on the scroll bar
![afterhover](https://user-images.githubusercontent.com/50016070/114495971-5641bc80-9c1f-11eb-9f68-c4366be8ad05.JPG)

**Comment by MennaMagdy2019** [comment]
it will look nice, Can I work on this issue please @fave77?
I am a GSSOC participant,Let me know if there is any modification
