### ISSUE TITLE
Fix the Navbar Dropdown and LogOut

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#12]
**Describe the bug** :bug:
The current dropdown in the navbar has the following issues:
- The background color and the text color are the same
- It overflows in the desktop view
- It takes up the entire viewport in mobile view
- After clicking logout, the UI doesn't change and needs a manual reload

**To Reproduce** :mag:
1. Go to `/register` or `/login` page
2. Register or Login as a user
3. Click on your username dropdown

**Expected behavior** :honeybee:
- Background color should be `#1d1e22`
- Text color should be `rgba(255, 255, 255, 0.5)`
- The dropdown shouldn't overflow in the desktop view
- Clicking on the logout should rerender the navbar and the `Login` link must appear instead of 'username (dropdown)'

**Screenshots** :camera:
- Desktop

![desktop](https://drive.google.com/uc?export=view&id=1NdaLiazj4RmKSksI2Br8wN1rdZnaj_qi)

![desktop](https://drive.google.com/uc?export=view&id=1HSc1KuPY_cZneYh1PNhWQsaxlAUzHu0g)

- Smatphone
![smartphone](https://drive.google.com/uc?export=view&id=1dxgrznMDAKpOd1Fj4yKxSK3sVtZcx-AW)

**Desktop (please complete the following information):** :computer:
 - OS: [e.g. e.g. ubuntu 20.04]
 - Browser [e.g. chrome]
 - Version [e.g. 87]

**Smartphone (please complete the following information):** :iphone:
 - Device: [e.g. pixel 2]
 - Browser [e.g. chrome]
 - Version [e.g. 87]

**Additional context** :memo:
NA

**Comment by pankajbijarniya** [comment]
I would like to contribute as a participant of JWOC.

**Comment by fave77** [comment]
@pankajkumarbij will assign you once the coding phase starts

**Comment by fave77** [comment]
@pankajkumarbij your allocated time is up.... so unassigning you from this issue

**Comment by Subhra264** [comment]
Hello I want to work on this issue under jwoc...

**Comment by fave77** [comment]
@Subhra264 Sure, assigning you...
