### ISSUE TITLE
Contributers Card

### ISSUE THREAD

**Issue by MennaMagdy2019** [fave77/pbchess#126]
**Describe the bug** :bug:
the contributes Card is not responsive or  does not look good on this screen 

**Expected behaviour** :honeybee:
I will make each card in each row or less width each card in col which you prefer? @fave77 

**Screenshots** :camera:
![Card](https://user-images.githubusercontent.com/50016070/115039663-f1ad8880-9ed0-11eb-90cf-c1511f218454.JPG)

**Comment by MennaMagdy2019** [comment]
Can I work on this bug, please? @fave77

**Comment by fave77** [comment]
@MennaMagdy2019 make it one card a row for smaller devices and also redesign the cards without borders

**Comment by fave77** [comment]
Can you provide a mockup for such a redesign? Will assign you then!

**Comment by MennaMagdy2019** [comment]
I removed the borders of the card but I didn't remove the box-shadow

![Card1](https://user-images.githubusercontent.com/50016070/115127913-7637fe00-9fda-11eb-9783-0368a050ef91.JPG)

and on haver
![Card2](https://user-images.githubusercontent.com/50016070/115128266-d3cd4a00-9fdc-11eb-8f06-e905c2457036.JPG)

Is it Ok or you prefer another style @fave77?

**Comment by fave77** [comment]
@MennaMagdy2019 yes remove the border and make the box-shadow, like so:
`box-shadow: 0px 0px 20px #8299fd;`

Check for yourself which one looks better if we add box-shadow while on hover, or it should disappear while hovering

**Comment by MennaMagdy2019** [comment]
I made the card like this
without haver
![Card befor](https://user-images.githubusercontent.com/50016070/115184530-4f62f000-a0de-11eb-800a-0dd4569122fc.JPG)
on haver
![Card after](https://user-images.githubusercontent.com/50016070/115184567-5b4eb200-a0de-11eb-8aef-30f8eef4166f.JPG)

I think it looks nice
What is your opinion? Is It Ok?
and Can you assign me this issue please to make a pull request?  @fave77
