### ISSUE TITLE
Navbar on haver and scroll

### ISSUE THREAD

**Issue by MennaMagdy2019** [fave77/pbchess#127]
**Is your feature request related to a problem? Please describe.** :bulb:
Can I make background color for links on hover like this
![navbar1](https://user-images.githubusercontent.com/50016070/115047043-6e903080-9ed8-11eb-9008-4ccfc8546006.JPG)

 and I want to make a shadow for the navbar on a scroll only  as of the shadow of the contributor card like this
![navbar3](https://user-images.githubusercontent.com/50016070/115047945-540a8700-9ed9-11eb-8b11-61199d53207f.JPG)

and when hover on links on the navbar and scroll it look like
![navbar2](https://user-images.githubusercontent.com/50016070/115048108-8320f880-9ed9-11eb-9718-372b3859b4d6.JPG)

I  think it will look nice and better.

**Comment by MennaMagdy2019** [comment]
Can you assign me this issue, please? @fave77 
and if you prefer another style can you tell me

**Comment by fave77** [comment]
@MennaMagdy2019 just make the hover for nav links 

![](https://user-images.githubusercontent.com/50016070/115047043-6e903080-9ed8-11eb-9008-4ccfc8546006.JPG)
