### ISSUE TITLE
Landing Page Image and navbar overlapping

### ISSUE THREAD

**Issue by VishalPatil18** [fave77/pbchess#138]
**Describe the bug** :bug:
When the page is scrolled down the image overlaps with the navbar.

**To Reproduce** :mag:
1. Go to the site
2. Scroll down the landing page
4. See overlapping navbar and image

**Expected behaviour** :honeybee:
It shouldn't overlap

**Screenshots** :camera:
![Screenshot 2021-05-07 at 10 28 44](https://user-images.githubusercontent.com/62737267/117399950-487e0f00-af1f-11eb-992a-98ecbfd31b32.png)

**Desktop (please complete the following information):** :computer:
 - OS: iOS
 - Browser: safari
 - Version: 13.1.3

**Additional context** :memo:
I would like to fix this under GSSoC21

**Comment by VishalPatil18** [comment]
@MennaMagdy2019 can you assign this to me under GSSoC21?

**Comment by fave77** [comment]
@SpecTEviL updates please?

**Comment by VishalPatil18** [comment]
I've created a PR. Please review @fave77.
I tried 2-3 different methods but they weren't working hence had to refer to google and thus it took time.
