### ISSUE TITLE
adding time clock

### ISSUE THREAD

**Issue by Sowmya-Betina** [fave77/pbchess#143]
I want to add a time clock to the platform using HTML functions and time modules to make the operations much easy to use and feasible

**Comment by adi-g15** [comment]
@Sowmya-Betina There is already a clock in the play mode as of now.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/37269665/119274050-9a1adf00-bc2b-11eb-884a-ff8d29e83ce9.png">

If you wanted to add a clock to some other part, do tell us.

EDIT: Or maybe something similar to #85 ?
