### ISSUE TITLE
Please add env Variables Information

### ISSUE THREAD

**Issue by jsonpreet** [fave77/pbchess#150]
Please add env Variables Information it's not easier to get all variables from files and create env file. for client and server

**Comment by apurv-1** [comment]
You can find all the resources to set up the local env [here](https://github.com/fave77/pbchess/blob/develop/.github/CONTRIBUTING/CONTRIBUTING.md#construction-setup-local-environment). Hope this helps!

**Comment by jsonpreet** [comment]
Ok thank you
