### ISSUE TITLE
Create a 'videos' component for displaying lichess TV

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#23]
**Is your feature request related to a problem? Please describe.** :bulb:
N/A

**Describe the solution you'd like** :sparkles:

- Visit [https://lichess.org/developers](https://lichess.org/developers) for how to embed the lichess TV
- Theme should be set to `blue-marble`

**Describe alternatives you've considered** :star2:
N/A

**Additional context** :memo:
N/A

**Comment by Devenkapoor7303** [comment]
Can I work on this issue as a part of GSSOC 21

**Comment by fave77** [comment]
@Devenkapoor7303 Sure 👍🏻 
But may I know your discord username first?

**Comment by Devenkapoor7303** [comment]
my discord username is deven

**Comment by fave77** [comment]
@Devenkapoor7303 Embed the `videos` component at the bottom of the `learn` component

**Comment by Devenkapoor7303** [comment]
Okay I will start the work on the issue from today onwards

**Comment by fave77** [comment]
@Devenkapoor7303 any update please?

**Comment by Devenkapoor7303** [comment]
Yeah I was working on it .Today at night I will share a png of final design and will make a PR

**Comment by fave77** [comment]
@Devenkapoor7303 Okay

**Comment by Devenkapoor7303** [comment]
@fave77  I have added the videos with aligning it to the center can u review it so that I can make a PR.

![Capture](https://user-images.githubusercontent.com/73438023/110442942-3cd1b180-8070-11eb-927f-1d85f0920d32.PNG)

**Comment by fave77** [comment]
@Devenkapoor7303 looks fine to me 👍🏻

**Comment by Devenkapoor7303** [comment]
okay I am making PR then
