### ISSUE TITLE
Provide an article on chess - Grokking Chess: Fundamentals, Principles, and Checkmate Patterns

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#24]
**Is your feature request related to a problem? Please describe.** :bulb:
This article is for the learning section of pbchess.

**Describe the solution you'd like** :sparkles:
Provide an article under 1000 words that also fulfill 5 min read time. It should consist of plenty of images, elaborations wherever it needs. Simply put, it should be visually stunning and engaging, and must be submitted as a Markdown file named `grokking_chess.md` inside `.github/lessons/`.

The title for the articles is - **Grokking Chess: Fundamentals, Principles, and Checkmate Patterns**
- It should contain three sections such as fundamentals, principles, and checkmate patterns
- You can take help or insights from any resources but make sure it isn't plagiarized.
- The fundamentals would focus mainly on how to play chess, basic history, how the pieces work, how to set the board, etc.
- The principles would talk about tactics, strategies, opening theories, etc.
- The checkmate patterns would focus on ...well checkmates of course but also endgames, stalemate patterns, and so on...
- Lastly, [https://smallseotools.com/plagiarism-checker/](https://smallseotools.com/plagiarism-checker/) should reflect the plagiarism to be less than 15%
- The article needs to be free of basic grammatical errors so consider using [Grammarly](https://app.grammarly.com/)!

**Describe alternatives you've considered** :star2:
NA

**Additional context** :memo:
Do note that the issue is marked as `moderate` for a reason, not so much on the requirements but on expectations. Feel free to reach out to discuss crafting it.

**Comment by Anjali041** [comment]
I would like to work on this issue, kindly assign it to me. I am GSSoC'21 participant.

**Comment by fave77** [comment]
@Anjali041 please state your discord username

**Comment by Anjali041** [comment]
Anjali#5463
