### ISSUE TITLE
Provide an article on chess - Chess Engines 101: Looking through the Machine’s Lens

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#25]
**Is your feature request related to a problem? Please describe.** :bulb:
This article is for the learning section of pbchess.

**Describe the solution you'd like** :sparkles:
Provide an article under 1000 words that also fulfill 5 min read time. It should consist of plenty of images, elaborations wherever it needs. Simply put, it should be visually stunning and engaging, and must be submitted as a Markdown file named `chess_engines.md` inside `.github/lessons/`.

The title for the article is - Chess Engines 101: Looking through the Machine’s Lens
- It should briefly explain what is a chess engine
- How it works under the hood
- Basic algorithms and idea that goes into making chess engines
- Give a specific example of a chess engine with `Stockfish`, talk about its success and ratings a bit
- Later, move on to AlphaZero, its success, and inner workings a bit
- Lastly, discuss the dichotomy of AlphaZero and traditional chess engines like Stockfish
- End the article posing an open-ended question on how the chess engines would evolve in the near future and what that means for us humans
- The article needs to be free of basic grammatical errors so consider using [Grammarly](https://app.grammarly.com/)!

**Describe alternatives you've considered** :star2:
NA

**Additional context** :memo:
Do note that the issue is marked as `moderate` for a reason, not so much on the requirements but on expectations. Feel free to reach out to discuss crafting it.

**Comment by Adrenalinerush07** [comment]
Hello, being a chess player I will really love to work on this issue.
[Chess profile](https://www.chess.com/member/anshuchiha)

**Comment by fave77** [comment]
@Adrenalinerush07 please provide your gssoc's discord username

**Comment by Adrenalinerush07** [comment]
It's KartikJaiswal#6870

**Comment by midhun-b-m** [comment]
Hello @fave77,
I would like to help craft a good article in satisfying the given criteria. 
Some of my writings can be found at https://midhunbm.com (if required)
Please consider me to help resolve this issue.
I am a participant at GSSoC'21 
**My discord username**: whoismbm#5713

**Comment by fave77** [comment]
@midhun-b-m please understand that it has already been assigned to another person, you could contribute by raising an issue on a new article though.... let's discuss over discord if you're interested - fave77#0087 (my discord username, just ping me over there)

**Comment by adi-g15** [comment]
@Adrenalinerush07 Can you share your progress on this issue ?

**Comment by adi-g15** [comment]
@fave77 I think the issue can be unassigned, as there hasn't been a response for some time.

**Comment by shreyadubey0902** [comment]
can you assign this to me if it's not done yet!

**Comment by fave77** [comment]
@shreyadubey0902 please confirm whether you're a gssoc participant by sharing your discord username

**Comment by shreyadubey0902** [comment]
Yes i m a participant in gssoc21....my discord username is shreya_(P)#6485

**Comment by fave77** [comment]
@shreyadubey0902 please share your update

**Comment by Sreelayavuyyuru** [comment]
I can see that there is a file named grokking_chess.md inside the Lessons folder that you mentioned. Should we make changes in the file? 
I would like to work on this.

**Comment by 1vivekanand** [comment]
@fave77  would like to contribute in this issue under GSSoC'21. Please assign it to me as I love playing chess. My discord username is Vivekanand Bhardwaj#7825

**Comment by fave77** [comment]
@1vivekanand update, please?

**Comment by 1vivekanand** [comment]
@fave77  May I get your discord username. I want to discuss something

**Comment by fave77** [comment]
@1vivekanand it's `fave77#0087`

**Comment by subhangi2731** [comment]
please assign me this issue

**Comment by ASLManasa** [comment]
I am gssoc'21 Partcipant and would like to work on this. Thank you

**Comment by adi-g15** [comment]
> 
> 
> I am gssoc'21 Partcipant and would like to work on this. Thank you

@ASLManasa the issue is already assigned to a gssoc participant as of now. You maybe assigned if @subhangi2731 is not working on it.

**Comment by adi-g15** [comment]
@subhangi2731 Can you please give us an update on the issue ?

**Comment by ASLManasa** [comment]
@adi-g15 Ok ! sure Thanks!

**Comment by fave77** [comment]
@ASLManasa would be interested in working on this issue?

**Comment by ASLManasa** [comment]
@fave77 yeah sure! just let me know how much content do you require!

**Comment by fave77** [comment]
> @fave77 yeah sure! just let me know how much content do you require!

please read the issue description

**Comment by ASLManasa** [comment]
@fave77  I have started working will update you asap. stuck with some college work. Thanks

**Comment by fave77** [comment]
@ASLManasa updates please?

**Comment by harshita2319** [comment]
Hey, I'm a GSSOC participant and I'd like to work on this issue!
@fave77

**Comment by fave77** [comment]
@harshita2319 please make the PR by tomorrow EOD otherwise I will have to unassign you

**Comment by harshita2319** [comment]
I've completed the article but there's already a file with that name in the lessons folder. So should I just add this content there only or create another file. If yes, then please specify the name of the file too.

> @harshita2319 please make the PR by tomorrow EOD otherwise I will have to unassign you
