### ISSUE TITLE
Your/opponent turn prompt

### ISSUE THREAD

**Issue by OmkarPh** [fave77/pbchess#26]
**Is your feature request related to a problem? Please describe.** :bulb:
There should be a Your/Opponent turn prompt or label on screen. It would be very helpful.
For example, user might take eyes off screen for couple of seconds and miss the opponent's movement. He/she would keep waiting for opponent and opponent would also have to wait. That is not at all good.

**Describe the solution you'd like** :sparkles:
We can add a small text to bottom-right/left of screen showing either:
Your turn (Green) or
Opponent's turn (Gray)

Edit: We can add animation for Your turn also to catch attention 

Can you assign this to me?

**Additional context** :memo:
Something like:
![image](https://user-images.githubusercontent.com/48476025/110417066-e2117780-80ba-11eb-9b35-b6b44ee6a7f9.png)

**Comment by fave77** [comment]
@OmkarPh It's a wonderful suggestion! Do you think we could maybe display the username of the players on the top-left and bottom-left side of the board. 
And the player's username would be highlighted upon his/her turn, maybe a little wiggle animation. I agree it is a little implicit, but what do you think?

**Comment by OmkarPh** [comment]
Ya that would be great. 
For larger screens we can show the status on top-left & bottom-left.
For smaller screens, can we show it above & below board ...?

Is it ok to have it this way:
bottom: Your move
top: john's move

**Comment by fave77** [comment]
@OmkarPh Yes, I meant above and below board actually for all the form factors. Like so,
![desktop](https://drive.google.com/uc?export=view&id=1H5mAVflN33KjLAr9BnIh800vDKqQGRex)
On the top-right and bottom-right, there would be timers for which I will open an issue later.

**Comment by fave77** [comment]
The green dot indicator could be used to show whose move it is

**Comment by OmkarPh** [comment]
Ya, it looks good.
Have you started with this already?

**Comment by fave77** [comment]
> Ya, it looks good.
> Have you started with this already?

Nope

**Comment by fave77** [comment]
@OmkarPh you're a GSSoC'21 participant?

**Comment by OmkarPh** [comment]
> @OmkarPh you're a GSSoC'21 participant?

Yes, found this repo through GSSoC projects page

I know I became a bit desperate. Sorry for opening hasty issue XD

**Comment by fave77** [comment]
@OmkarPh No, your suggestion was great 👍🏻 
I was just asking whether to add the gssoc tag or not!
Anyway, assigning you now... but first please share your discord username

**Comment by OmkarPh** [comment]
> @OmkarPh No, your suggestion was great 👍🏻

I meant the other one ;)

> Anyway, assigning you now... but first please share your discord username

Omkar Phansopkar (P)#8349

**Comment by OmkarPh** [comment]
@fave77 I tried modifying the code, but realised that after every small change, I have to create and join a new room again.
Is there any way to do this efficiently?

**Comment by fave77** [comment]
@OmkarPh let's connect over discord
