### ISSUE TITLE
Suggestion: Add contributing guidelines

### ISSUE THREAD

**Issue by OmkarPh** [fave77/pbchess#27]
**Is your feature request related to a problem? Please describe.** :bulb:
Any new contributor has to figure about project structure and has to spent quite some time figuring it out. It would be very helpful if there is a contributing guidelines for their help.
I am also new to this repo. Admins may look after it.

**Describe the solution you'd like** :sparkles:
Add CONTRIBUTING.md file with steps
Add .env.sample file providing default environment variables (May I do this part?)

**Comment by fave77** [comment]
@OmkarPh The contributing guidelines already exist. For your reference, please check [CONTRIBUTING.md](https://github.com/fave77/pbchess/blob/develop/.github/CONTRIBUTING/CONTRIBUTING.md)

**Comment by OmkarPh** [comment]
Oops ! 
My bad ;)
