### ISSUE TITLE
Provide an article on chess - Chess Vocab: Speaking the common tongue

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#29]
**Is your feature request related to a problem? Please describe.** :bulb:
This article is for the learning section of pbchess.

**Describe the solution you'd like** :sparkles:
- Provide a list of all possible chess-related words in alphabetical order along with one or two-line descriptions for each.

**Describe alternatives you've considered** :star2:
NA

**Additional context** :memo:
NA

**Comment by srisatya12** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by fave77** [comment]
@srisatya1197 please provide your GSSoC'21 discord username

**Comment by MayankBeck** [comment]
I want to work on this issue. Please assign this task to me as a part of GSSoC 21.

**Comment by fave77** [comment]
@srisatya1197 @MayankBeck this issue will be assigned to whoever confirms their own discord username for GSSoC'21 first

**Comment by feni-katharotiya** [comment]
@fave77 Hello, I am gssoc participant and would like to work on this issue.

discord  username :  feni#4332

**Comment by feni-katharotiya** [comment]
@fave77 Hello, I am gssoc participant and would like to work on this issue.
discord username : Feni#4332

**Comment by fave77** [comment]
@feni-katharotiya already assigned you to issue #28

**Comment by Arshanshagarwal** [comment]
Hi, I want to work on this issue.
Discord Username:  Arshansh#5364

**Comment by feni-katharotiya** [comment]
> @feni-katharotiya already assigned you to issue #28 

Okay

**Comment by Shivam648** [comment]
Hi, am GSSOC21 participant and I want to work on this issue. 
Discord Username-  Shivam Jaiswal(P)#4469

**Comment by fave77** [comment]
@Shivam648 It has already been assigned to @Arshanshagarwal 
Please find a different issue and/or raise your own to work on 👍🏻

**Comment by Shivam648** [comment]
@fave77 it:s ok
