### ISSUE TITLE
Adding script to install all packages at once

### ISSUE THREAD

**Issue by rithgan** [fave77/pbchess#33]
**Is your feature request related to a problem? Please describe.** :bulb:
It's always easier and faster to install all packages on the server and the client-side by running one script

**Describe the solution you'd like** :sparkles:
I will add the "setup" script to the package.json in the root directory through which all packages on both sides will be installed simultaneously. 

**Describe alternatives you've considered** :star2:
There are not many alternatives to be discussed since this is more an improvement than a feature

**Additional context** :memo:
This will be very helpful in the quick setup of the project

**Comment by rithgan** [comment]
If this issue gets approved, I would like it to be assigned to me for gssoc.

**Comment by fave77** [comment]
@rithgan like a single `npm install` on root **package.json** ?

**Comment by rithgan** [comment]
Yes like that. I have already written it. One will have to run 
> npm run setup

and all packages will be installed

**Comment by fave77** [comment]
@rithgan Script written inside `package.json` or calls some `.sh` files

**Comment by rithgan** [comment]
It will be written in package.json only but can also be written in .sh file

**Comment by fave77** [comment]
Fine let's keep it in the package.json since it would be quite simple

**Comment by fave77** [comment]
@rithgan also update this part of the CONTRIBUTING.md like so:
```bash
# clone the forked repository to your local machine
$ git clone https://github.com/<YOUR-GITHUB-USERNAME>/pbchess.git

# navigate to the project's directory
$ cd pbchess

# install the dependencies for both client and server
$ npm run setup

# install just the client dependencies
$ cd client && npm install

# install just the server dependencies
$ cd server && npm install
```

**Comment by rithgan** [comment]
Okay i am on it.
