### ISSUE TITLE
Adding Avatar to Profile Picture

### ISSUE THREAD

**Issue by apurv-1** [fave77/pbchess#35]
**Is your feature request related to a problem? Please describe.** :bulb:
No

**Describe the solution you'd like** :sparkles:
1. Profile avatar for the users. Like this 👇
![Capture](https://user-images.githubusercontent.com/53378650/110516541-b9779500-812f-11eb-9f09-f464c69ab3be.PNG)
2. The profile model on the server should be changed from String to ObjectId. and the same changes have to be made on apis.
![Capture](https://user-images.githubusercontent.com/53378650/110520265-3efd4400-8134-11eb-9cce-b5ce5b19bb49.PNG)

**Describe alternatives you've considered** :star2:
You can make use of this npm package: https://www.npmjs.com/package/getavataaars
demo: https://getavataaars.com/

**Additional context** :memo:
These are some properties, which should be implemented.
![pbchess](https://user-images.githubusercontent.com/53378650/110516313-70274580-812f-11eb-9955-fd8249f0a240.PNG)

**Comment by jain-rishabh-21** [comment]
Please assign it to me.
discordUsername: krackerzzz#4371

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me under GSSOC'21?

**Comment by jain-rishabh-21** [comment]
I am already working on it!

**Comment by adi-g15** [comment]
@jain-rishabh-21 Can you provide update on this issue ?

**Comment by jain-rishabh-21** [comment]
Hi, I am currently stuck at one point on this issue!

**Comment by apurv-1** [comment]
Let us know, were you're stuck. So that we can help you out!

**Comment by jain-rishabh-21** [comment]
Yes @apurv-1 I was not familier with ts, so it took some time ! I will get to you on discord if I face any difficulty !

**Comment by apurv-1** [comment]
@rk05-lenavo are you still interested in this?

**Comment by Sreelayavuyyuru** [comment]
I am interested in this, Could you please assign this to me?
My discord username is Sreelaya (P)#7527

**Comment by fave77** [comment]
@Sreelayavuyyuru update, please?

**Comment by Sreelayavuyyuru** [comment]
> @Sreelayavuyyuru update, please?

I cannot complete it, please assign it to someone else

**Comment by tend2infinity** [comment]
Hey , I would like to work on this issue under GSSOC, please assign that to me

**Comment by apurv-1** [comment]
@tend2infinity any update on this?

**Comment by tend2infinity** [comment]
@apurv-1 I told some of my issues to @fave77 on discord. Hope you understand!. Still, I'm gonna work on this issue today and will make a pr tomorrow at the earliest

**Comment by apurv-1** [comment]
@tend2infinity any update?

**Comment by tend2infinity** [comment]
yup @apurv-1 I just completed my end sem exams, I have already done some work earlier soo, I would just need few hours to make a new PR, please bear with me, I know it has been a long time but thank you for your patience, from now onwards I'll try to be very active!

**Comment by subhangi2731** [comment]
@fave77 please assign me I will send a pr within 2 days my discord username is subhangi#9516
