### ISSUE TITLE
Rule for all pieces of chess as part of gssoc'21 

### ISSUE THREAD

**Issue by krishna-y2000** [fave77/pbchess#36]
**Is your feature request related to a problem? Please describe.** :bulb:
There are people who don't know the rules of chess pieces. It would be good if there is a written set of rules section of pieces like how a queen can move, how pawn can move and kill opponent etc 

**Describe the solution you'd like** :sparkles:
I would like to add tab of rules on navigation bar which would describe the rules of all the chess pieces.
Please assign this issue to me as part of gssoc'21.
My Discord Username : kyadav#6342

**Comment by fave77** [comment]
@krishna-y2000 What you are proposing is going to be implemented inside the `/learn` route by rendering a component called `Lessons`. Please refer to the issue #24 and the [article](https://github.com/fave77/pbchess/blob/develop/.github/Lessons/grokking_chess.md).

`/learn` would also render `Videos` (#23 )and `Puzzles`(#22) along with `Lessons` in the form of tabs for displaying one component at a time.
