### ISSUE TITLE
[GSSOC'21] Improve Readme 

### ISSUE THREAD

**Issue by krishna-y2000** [fave77/pbchess#38]
**Is your feature request related to a problem? Please describe.** :bulb:
There are few things missing in readme like how to get started for developers , features of projects etc

**Describe the solution you'd like** :sparkles:
I would edit the readme file and make it better . It will be easy to understand for developers.

Please asssign this issue to me as part of gssoc'21.
My Discord Username : kyadav#6342

**Comment by fave77** [comment]
> There are few things missing in readme like how to get started for developers , ...
 
@krishna-y2000 This has been thoroughly described in `CONTRIBUTING.md`

> I would edit the readme file and make it better . It will be easy to understand for developers.

You mentioned **features of projects**, please elaborate how you are going to illustrate that? FYI, the [project demo](https://github.com/fave77/pbchess/wiki/Project-Demo) already exists.

**Comment by fave77** [comment]
Closing the issue due to no response
