### ISSUE TITLE
Adding Google Authentication 

### ISSUE THREAD

**Issue by Coder-Srinivas** [fave77/pbchess#39]
**Is your feature request related to a problem? Please describe.** :bulb:
The website is lacking Google and Facebook sign in feature

**Describe the solution you'd like** :sparkles:
I would like to add sign in with google and sign in with Facebook features.

Please assign me this issue under GSSoC 2021

**Comment by fave77** [comment]
@Coder-Srinivas let's work with Google first, and please lay out a detailed picture of all the libraries, API-keys you'll be using for this issue

**Comment by Coder-Srinivas** [comment]
@fave77 I would be using OAuth2.0 to access the Google API's and the Passport npm module. In order to access the Google API, we need a client id and the client secret key. In order to get them we need a Google account. Should I create a new google account in order to get them? Please suggest.
My Discord Username is : Srinivas(P)#7368

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by fave77** [comment]
@rk05-lenavo this issue is already assigned ...please raise your own issue to work on (if approved) otherwise wait for a couple of days for new issues to be rolled out
