### ISSUE TITLE
Make the homepage carousel responsive and readable

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#4]
**Describe the bug** :bug:
The carousel seems to be non-responsive on smaller form factors and tends to overflow from the viewport. The quote isn't readable due to it being overlaid onto the image.

**To Reproduce** :mag:
1. Go to the homepage

**Expected behavior** :honeybee:
A responsive carousel card that consists of the image at the top and a quote at the bottom. The bg color for the card must be different than that of the bg color of the homepage as well as that from the quote's text color. The width of the card must be 70-80% of the viewport width depending on the device.

**Screenshots** :camera:
- Desktop
![desktop](https://drive.google.com/uc?export=view&id=1B2aDH4xoU2oexpoITlZp02Uo8dBTPA0S)

- Smartphone
![smartphone](https://drive.google.com/uc?export=view&id=1p4hDqnwj8dYrvhiSZNoG9UavlyiOijtV)

**Desktop (please complete the following information):** :computer:
 - OS: [e.g. ubuntu 20.04]
 - Browser [e.g. chrome]
 - Version [e.g. 87]

**Smartphone (please complete the following information):** :iphone:
 - Device: [e.g. redmi k20 pro]
 - OS: [e.g. android 10]
 - Browser [e.g. chrome]
 - Version [e.g. 87]

**Additional context** :memo:
NA

**Comment by sorbx64** [comment]
Hi @fave77, I would like to contribute to your project starting with this issue.

**Comment by fave77** [comment]
Sure! If you face any hurdles, do reach out.

**Comment by sorbx64** [comment]
Sure i will. Thanks.

**Comment by sorbx64** [comment]
Hi @fave77, I added react-bootstrap card to the carousel in home and css-in-js so that now it's responsive, but card is also inheriting styles from app.css. So, could you help me by telling if card styles (below in images) alright? And should I use css-in-js or make new home.css and import it in home.js to overwrite app.css effects on card in home?

![localhost_3000_(iPhone-X)](https://user-images.githubusercontent.com/60147716/103454098-700d6280-4d06-11eb-8961-cf5dd6b17fc4.png)

**Comment by fave77** [comment]
Hi @saurabh-33 looks good, this will do for now 👍🏻 
However, I have been thinking about redesigning the entire site using glassmorphism; let me know if you are interested to contribute in the design decisions, so that we can delegate the task among ourselves properly.
In the meantime, make the PR regarding this issue.

**Comment by sorbx64** [comment]
> Hi @saurabh-33 looks good, this will do for now 👍🏻
> However, I have been thinking about redesigning the entire site using glassmorphism; let me know if you are interested to contribute in the design decisions, so that we can delegate the task among ourselves properly.
> In the meantime, make the PR regarding this issue.

Of course @fave77, I am also interested in glassmorphism design, So count me in.

I have made the PR for this issue. Please check it and let me know if any edits needed.
