### ISSUE TITLE
Provide Join/create instead option

### ISSUE THREAD

**Issue by OmkarPh** [fave77/pbchess#40]
**Is your feature request related to a problem? Please describe.** :bulb:
Assuming the following situation:
A user might have code for a room. He/she visited the play page, and clicked on `create game` by mistake instead of `join game`.
In such case, the user has to manually reload the page in order to click on join game again.
In order to prevent this, we can have a small link/button on the `lobby code` dialog, clicking on which user can cancel new room action and join to a game instead
Similar situations might hapeen the other way. Someone had to create a game, but click on join by mistake.

**Describe the solution you'd like** :sparkles:
A link/button to bottom-left of copy code dialog, similar to `Login instead` we see on sign up pages. It would cancel the create room process and replace it with the join room dialog.
Similar link/button to replace join room dialog with create room dialog
Additionally, what is the extra comma that appears after copy code button?
It is there by mistake, we can remove that if it is so.

**Additional context** :memo:
Something like this:
![image](https://user-images.githubusercontent.com/48476025/110739559-6862c080-8257-11eb-866f-3cd464a405fa.png)

**Comment by OmkarPh** [comment]
Can you assign this me under GSSoC 21

My discord: Omkar Phansopkar (P)

**Comment by OmkarPh** [comment]
Also, there are a few console.log statements lying around. Shouldn't we remove them?

**Comment by adi-g15** [comment]
@fave77  Seems a good addition to me 👍

> Additionally, what is the extra comma that appears after copy code button?
> It is there by mistake, we can remove that if it is so.

I think it's by mistake, take a look at the end of line 179->

https://github.com/fave77/pbchess/blob/4f4115592c24393481756838a62caa93dc13f704/client/src/components/lobby/lobby.js#L179-L181

**Comment by adi-g15** [comment]
> 
> 
> Also, there are a few console.log statements lying around. Shouldn't we remove them?

<img width="280" alt="console" src="https://user-images.githubusercontent.com/37269665/110746453-d95ba580-8262-11eb-9c87-cb00ba8c0c0a.png">

Seems you are talking about all these @OmkarPh ?

**Comment by OmkarPh** [comment]
> Seems you are talking about all these @OmkarPh ?

Yes

Should I remove them?

**Comment by fave77** [comment]
> > Seems you are talking about all these @OmkarPh ?
> 
> Yes
> 
> Should I remove them?

No need to remove console logs, they would come in handy while refactoring `lobby.js`

**Comment by OmkarPh** [comment]
> No need to remove console logs, they would come in handy while refactoring `lobby.js`


Ohk 👍
