### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [fave77/pbchess#41]
Hi! I would like to add contributing.md to the repo which states on how to clone and fork the repo,how to add ,create and push a repo,squash commits,rebase your feature branch ,how to update forked repo as well as local repo to the changes made in upstream.
I would like to work on this under GSSOC'21.

**Comment by adi-g15** [comment]
@khareyash05 CONTRIBUTING.md is already available for this repo. You can take a look at other issues, or if you find an issue, you can create one, and ask to be assigned then. 😄

https://github.com/fave77/pbchess/blob/develop/.github/CONTRIBUTING/CONTRIBUTING.md
