### ISSUE TITLE
can create  a video library of chess matches/chess moves

### ISSUE THREAD

**Issue by Priyanka7011** [fave77/pbchess#42]
**Is your feature request related to a problem? Please describe.** :bulb:

**Describe the solution you'd like** :sparkles:

**Describe alternatives you've considered** :star2:

**Additional context** :memo:

**Comment by adi-g15** [comment]
@Priyanka7011 Can you add some more details in the issue ?
It seems little vague from only having a title. A brief description of the feature will be helpful.
