### ISSUE TITLE
Landing Page UI

### ISSUE THREAD

**Issue by Sanchit-Soni** [fave77/pbchess#46]
**Describe the bug** :bug:
The Carousel arrow key is overlapping with the image of the chessboard.
The gradient colour which is used for the card is also too light according to the theme of the landing page

**To Reproduce** :mag:
Steps to reproduce the behaviour:
1. Go to 'https://develop--pbchess.netlify.app/'

**Expected behaviour** :honeybee:
The arrow key and image of the chessboard should not overlap with each other.
The gradient colour should also be a dark colour

**Screenshots** :camera:
![original pbChess](https://user-images.githubusercontent.com/61468328/110931978-e3f46880-8350-11eb-8f0d-ad74431352f8.png)

**Desktop (please complete the following information):** :computer:
 - OS: Windows10
 - Browser Chrome

**Comment by Sanchit-Soni** [comment]
I can fix this issue, Please assign this to me.
Discord Username: Sanchit(P)#7382

**Comment by fave77** [comment]
@Sanchit-Soni please provide a design mock-up first as to how you wanna improve this... and also state your screen size as well as browser version

**Comment by adi-g15** [comment]
> The arrow key and image of the chessboard should not overlap with each other.

It's fine on most screen sizes, though on big screen sizes I did found this, it can be fixed by changing the z-index of #carousal-control-next

Regarding the gradient colour I think it is a design choice 

@fave77 ?

**Comment by Sanchit-Soni** [comment]
Chrome version: Version 89.0.4389.82 (Official Build) (64-bit)
screen size 15.6" (1920 х 1080 pixels.)

![final pbchess](https://user-images.githubusercontent.com/61468328/110936312-b6122280-8356-11eb-8f26-d5e4cfedbd7d.png)

**Comment by apurv-1** [comment]
> > The arrow key and image of the chessboard should not overlap with each other.
> 
> It's fine on most screen sizes, though on big screen sizes I did found this, it can be fixed by changing the z-index of #carousal-control-next
> 
> Regarding the gradient colour I think it is a design choice
> 
> @fave77 ?

It's minor design change, @fave77 you can label it is as level 0 and good first issue.

**Comment by fave77** [comment]
@Sanchit-Soni just fix the positional error of the `arrow` and `board`, no need to modify the gradient color since it is a design choice
