### ISSUE TITLE
Adding Contributor section in the website 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [fave77/pbchess#47]
Original proposal 
> I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigned !!

Counter Proposal
> contributor list already exists on the repository's home page, it would be nice to create a page for the website though. /contributors would list all the contributors sorted by the number of commits and lines of code added.
The list would update automatically whenever a PR gets merged and it shouldn't contain bots as a contributor.
For the UI, on a 13-inch display, a row would contain 3 cards, and you can increase or decrease the number according to different form-factors, Each card would display the contributor's GitHub image, full name, username, and then clicking the card would redirect to their GitHub profile. Add animations for elevating the UX to a seamless experience.

Revised Proposal
> I believe adding contributors in a website would require it to load dynamically from contributor website which might require us to run that in the server as a scrapper for the website.
But the question arises that is it legal to scrape github webpages and abide by the policies

Final Proposal
> Let's say we compromise real-time update for getting rid of web scraping, then can you look into any GitHub APIs that exist for retrieving such data (even if it isn't real time). Maybe we could assign a scheduler to call the api once a day for updates. There is actually a github API for that, https://docs.github.com/en/rest/reference/repos#list-repository-contributors, found it through an answer on stackoverflow.
If you like the idea to show contributors at /contributors, you can have a look at it, there maybe more limitations but it also provides the number of contributions 👍 For this repo, it will be: https://api.github.com/repos/fave77/pbchess/contributors

**Comment by fave77** [comment]
@rohank2502 contributor list already exists on the repository's home page, it would be nice to create a page for the website though. `/contributors` would list all the contributors sorted by the number of commits and lines of code added. 
The list would update automatically **whenever a PR gets merged** and it shouldn't contain bots as a contributor.
For the UI, on a 13-inch display, a row would contain 3 cards, and you can increase or decrease the number according to different form-factors, Each card would display the contributor's GitHub image, full name, username, and then clicking the card would redirect to their GitHub profile. Add animations for elevating the UX to a seamless experience.
Let me know if you are up for this!

**Comment by rohan-kulkarni-25** [comment]
Ok I will think about it and will get back to you tomorrow !!

**Comment by fave77** [comment]
@rohank2502 sure!

**Comment by joshi008** [comment]
I believe adding contributors in a website would require it to load dynamically from [contributor website](https://github.com/fave77/pbchess/graphs/contributors) which might require us to run that in the server as a scrapper for the website. 
But the question arises that is it legal to scrape github webpages and abide by the [policies](https://docs.github.com/en/github/site-policy/github-privacy-statement)

**Comment by fave77** [comment]
@joshi008 can you suggest an alternative then?
Let's say we compromise real-time update for getting rid of web scraping, then can you look into any GitHub APIs that exist for retrieving such data (even if it isn't real time). Maybe we could assign a scheduler to call the api once a day for updates

**Comment by adi-g15** [comment]
> 
> 
> I believe adding contributors in a website would require it to load dynamically from [contributor website](https://github.com/fave77/pbchess/graphs/contributors) which might require us to run that in the server as a scrapper for the website.
> But the question arises that is it legal to scrape github webpages and abide by the [policies](https://docs.github.com/en/github/site-policy/github-privacy-statement)

@joshi008 There is actually a github API for that, https://docs.github.com/en/rest/reference/repos#list-repository-contributors, found it through an answer on stackoverflow.
If you like the idea to show contributors at `/contributors`, you can have a look at it, there maybe more limitations but it also provides the number of contributions 👍

For this repo, it will be: https://api.github.com/repos/fave77/pbchess/contributors

**Comment by joshi008** [comment]
@adi-g15 This api is good. Thanks for sharing it. Yes we can parse data from the info from this link. Would you like to contribute for it. I would be happy to contribute if no one takes.

**Comment by adi-g15** [comment]
> @adi-g15 This api is good. Thanks for sharing it. Yes we can parse data from the info from this link. Would you like to contribute for it. I would be happy to contribute if no one takes.

I am a mentor, so you can go ahead if you want to be assigned to this issue 🙂

**Comment by joshi008** [comment]
Sure, please assign me this issue 🙂.

**Comment by fave77** [comment]
@rohank2502 said he will let us know if he wants to work on this by today... so will wait for his reply. If we get no response, then will assign to you @joshi008 first thing tomorrow

**Comment by rohan-kulkarni-25** [comment]
Hey Rohan here I read the discussion @fave77  If @joshi008  want to go with this issue please assign him this !! Honestly I am having many issues assigned than just taking the issue as assigned and not completing is not good so I welcome the request of @joshi008 and request @fave77 to assign issue & If @joshi008 need any help I am ready to !!

**Comment by fave77** [comment]
> Hey Rohan here I read the discussion @fave77 If @joshi008 want to go with this issue please assign him this !! Honestly I am having many issues assigned than just taking the issue as assigned and not completing is not good so I welcome the request of @joshi008 and request @fave77 to assign issue & If @joshi008 need any help I am ready to !!

Thanks for the update! 👍🏻

**Comment by joshi008** [comment]
Hey @fave77 ,  where should this link be added for contributors?
I see two positions one at the navbar along with Login
or in the footer "Made with ❤️ by **our contributors** for the chess community" here **our contributors** will be a link diverted to this page.

The page looks like this 

![image](https://user-images.githubusercontent.com/54844760/111083632-76a12d00-8534-11eb-8258-15c42cff95e8.png)

Any suggestions for the page are welcome.

**Comment by fave77** [comment]
@joshi008 Add the link in the middle of the second row of footer in between license and support, named `Contributors`. Also, make sure the cards are animated, when page loads up and also responds on various gestures like hover, focus, etc.

**Comment by fave77** [comment]
@joshi008 you can use this [package](https://www.npmjs.com/package/react-animations)!
