### ISSUE TITLE
Make a footer for the homepage

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#5]
**Is your feature request related to a problem? Please describe.** :bulb:
Not necessarily.

**Describe the solution you'd like** :sparkles:
A footer component that renders the following three items:
- Made with ❤️ for the chess community
- [GPLv3 License](https://www.gnu.org/licenses/gpl-3.0.en.html) (links to the license page)
- [Support Us](https://github.com/fave77/pbchess) (links back to this repo)

**Describe alternatives you've considered** :star2:
NA

**Additional context** :memo:
Make the bg color for the footer the same as the header.

**Comment by somesh526** [comment]
Hi @fave77 can you assign me I will fix this issue under Jwoc

**Comment by fave77** [comment]
Hey @somesh526 issues will be assigned once the coding phase starts. Till then we can discuss about any improvement or features (that you might like to add) in our discord channel

**Comment by somesh526** [comment]
Hey @fave77 can you send the discord server link

**Comment by fave77** [comment]
@somesh526 You are a JWoC participant, right?
You must have received the discord link in your welcome mail

**Comment by somesh526** [comment]
I'm a JWOC participant, I registered as a mentee but I didn't received any email. If you are an organizer can you look into this issue if not can you tell me whom to reach to resolve this issue thank you @fave77

**Comment by somesh526** [comment]
@fave77 I got it the welcome mail is in the spam.Thank you no issues

**Comment by fave77** [comment]
@somesh526 Great 👍🏻

**Comment by sneha-baser** [comment]
as per instructions on taking up the issue on 21th Jan (Under JWOC), I am part of JWOC as mentee and i wanna contribute to this issue.

**Comment by fave77** [comment]
Sure @sneha-baser

**Comment by sneha-baser** [comment]
@fave77 i wants to ask is just 2 links that u described has to added.or can i also have to add links for social media handels??

**Comment by fave77** [comment]
@sneha-baser just the two links.... And footer must be only in homepage

**Comment by sneha-baser** [comment]
@fave77 I made PR but there is one condition not satisfy.. i am not able to get that one. could you please check.

**Comment by pankajkumarbij** [comment]
I would like to work on this issue.

**Comment by luckykumarirai** [comment]
@fave77 I would like to contribute as participant of GSSOC.

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by vieee** [comment]
Hi @fave77, I would like to contribute to this issue as a participant of GSSoC 21', Could I ?

**Comment by fave77** [comment]
@luckykumarirai @chehak123 @vieee I want to remind all of you that the official coding period of GSSoC 21' starts on 8th March according to the revised timeline! 
If you'd like to contribute now, that's fine for me but do note that that won't be counted under GSSoC 21'.
If you're fine with that, let me know and I will assign you 👍🏻 

PS: More issues coming, stay tuned 🚀

**Comment by maanpatel2492** [comment]
> **Is your feature request related to a problem? Please describe.** 💡
> Not necessarily.
> 
> **Describe the solution you'd like** ✨
> A footer component that renders the following three items:
> 
> * Made with ❤️ for the chess community
> * [GPLv3 License](https://www.gnu.org/licenses/gpl-3.0.en.html) (links to the license page)
> * [Support Us](https://github.com/fave77/pbchess) (links back to this repo)
> 
> **Describe alternatives you've considered** 🌟
> NA
> 
> **Additional context** 📝
> Make the bg color for the footer the same as the header.

Hey,
I can work very well on this issue.Assign if possible

**Comment by fave77** [comment]
@luckykumarirai @chehak123 @vieee @maanpatel2492 please state your discord username for the main GSSoC server.
This issue will be assigned on a first-come, first-serve basis as to whoever confirms 👍🏻

**Comment by jain-rishabh-21** [comment]
Discord username: krackerzzz#4371
Please assign the issue!

**Comment by RituCs** [comment]
I would like to contribute on this issue.can I start working?

**Comment by fave77** [comment]
@RituCs the issue is currently assigned to @jain-rishabh-21 , please find another issue to claim or raise your own issue for any bugs or feature

**Comment by MayankBeck** [comment]
I would like to work on this issue as a part of GSSoC 21.
