### ISSUE TITLE
Alerting the user via an email when he/she registers without using google.

### ISSUE THREAD

**Issue by Coder-Srinivas** [fave77/pbchess#51]
**Is your feature request related to a problem? Please describe.** :bulb:
The website lacks the feature of sending emails when a user registers himself/herself without using google. 

**Describe the solution you'd like** :sparkles:
I would like to use the nodemailer module to send emails to the client when a user registers without using google.

**Comment by Lza-etc** [comment]
Hi
would you mind me doing this using emailjs

**Comment by fave77** [comment]
@Lza-etc this issue is already assigned!
