### ISSUE TITLE
Learn page not scaling properly when viewed on mobile screen

### ISSUE THREAD

**Issue by Vanshikaa00** [fave77/pbchess#52]
**Describe the bug** :bug:
Learn page is not scaling accordingly when viewed on mobile screen. A lot of spacing on right side could be seen when you zoom out.

**To Reproduce** :mag:
1. Go to https://develop--pbchess.netlify.app/learn
2. Inspect the page and click on toggle device toolbar
3. Choose any mobile device, say galaxy s5
4. See the error

**Expected behaviour** :honeybee:
The page should scale out properly occupying full width of screen size available

**Screenshots** :camera:
![image](https://user-images.githubusercontent.com/53425575/111032529-b2ec6480-8432-11eb-90cb-59bffb678dec.png)

**Desktop (please complete the following information):** :computer:
- Works fine on desktop

**Smartphone (please complete the following information):** :iphone:
 - Device: Galaxy S5
 - Browser: Chrome

**Comment by Vanshikaa00** [comment]
@fave77 I would like to work upon this

**Comment by fave77** [comment]
@Vanshikaa00 please state your discord username on GSSoC server?

**Comment by Vanshikaa00** [comment]
It's Vanshika#7545  @fave77
