### ISSUE TITLE
Adding Contributor section in readme ( Automatically )

### ISSUE THREAD

**Issue by sahilempire** [fave77/pbchess#56]
I will like to add a feature this will **update contributor list** in README.md **automatically** !! Will start to work on this issue as soon as **I get assigned** !

Thank You

**Comment by adi-g15** [comment]
A similar issue is being worked upon, take a look at #47 

Also this proposal has been mentioned earlier:
![ditto](https://user-images.githubusercontent.com/37269665/111361695-f99cc180-86b3-11eb-9b37-a80f0c0e6244.png)

You may want to look at the code, and create one or work on another unassigned issue :smile:
@sahilempire You may like to close this issue since it's already been proposed

**Comment by adi-g15** [comment]
@fave77

**Comment by sahilempire** [comment]
okay then, I'm closing this issue.

Thank you

**Comment by adi-g15** [comment]
@sahilempire You can look up the code, and try the website if you find some issue, you can work on improving it, and ask us for difficulties faced :+1:

**Comment by sahilempire** [comment]
okay @adi-g15 ,

Thanks

**Comment by adi-g15** [comment]
Also @sahilempire **please** don't do it for the sake of just topping the leaderboard. I just found out there are 72 of these issues, and you would surely be knowing this.

**Comment by sahilempire** [comment]
@adi-g15 I really don't think like that, but you think this about me and surely this is only my fault.
I sincerely Sorry for this,
but before adding this issue, I just go through the README.md file and their is no contribution section at all, so I just simply added this issue.

**Comment by adi-g15** [comment]
> @adi-g15 I really don't think like that, but you think this about me and surely this is only my fault.
> I sincerely Sorry for this,
> but before adding this issue, I just go through the README.md file and their is no contribution section at all, so I just simply added this issue.

Okay, good to hear that you don't think solely of the leaderboard, have a fun journey trying out projects and helping them be better 😄👍

**Comment by adi-g15** [comment]
> @adi-g15 I really don't think like that, but you think this about me and surely this is only my fault.
> I sincerely Sorry for this,
> but before adding this issue, I just go through the README.md file and their is no contribution section at all, so I just simply added this issue.

https://github.com/search?q=Adding+Contributor+section+in+readme+%28+Automatically+%29+author%3Asahilempire+updated%3A%3E2021-03-07&type=Issues&ref=advsearch&l=&l=
