### ISSUE TITLE
Add Login with Lichess

### ISSUE THREAD

**Issue by JadeMaveric** [fave77/pbchess#57]
**Is your feature request related to a problem? Please describe.** :bulb:
Lichess now offers [OAuth](https://lichess.org/api#section/Authentication), which means a "Login with Lichess" button is within reach. And although it sounds ironic, it would be the epitome of foss+chess enthusiasm to include such a button.

**Describe the solution you'd like** :sparkles:
Add the "Login with Lichess" button (under the google one). All sensitive variables will be stored in the .env file so that the maintainers can replicate [the app](https://lichess.org/account/oauth/app/create) in production.

**Describe alternatives you've considered** :star2:
Not including the bu.... gosh, I can't even fathom such a thing 😨 

**Additional context** :memo:
♟️ + ☮️  = ❤️ 
[gsSoC '21]

**Comment by fave77** [comment]
> Not including the bu.... gosh, I can't even fathom such a thing :fearful:

Very sneaky way to put someone on the spot! : 😅
Don't worry will assign you, just share your GSSoC'21 discord username...

PS - I love [lichess](https://lichess.org/@/fave77)!

**Comment by JadeMaveric** [comment]
Thanks! I'll get started on a PR.
>  Very sneaky way to put someone on the spot! : sweat_smile

Sorry, didn't meant to make it awkward 🙈 

I'm JadeMaveric#2187 on Discord

PS - Foss yeah! [lichess](https://lichess.org/@/JadeMaveric) >>>> [chess](https://www.chess.com/)

**Comment by fave77** [comment]
@JadeMaveric PR for issue #54 will be made by today. Make sure to pull those changes too since it will consist of several modifications on the server side code
