### ISSUE TITLE
Allow playing with bots

### ISSUE THREAD

**Issue by JadeMaveric** [fave77/pbchess#58]
**Is your feature request related to a problem? Please describe.** :bulb:
Sometimes I burn the midnight oil and during my breaks crave nothing more than a short bullet game. But my friends seem really upset when I call them up and send them the pbchess game ID to my game. 😭  One of them even threatened to mute/block/unfollow me!
I have since decided that I shall make new friends, and the most strategic choice is to get chummy with our future overlords.

**Describe the solution you'd like** :sparkles:
I'd like to be able to play against AI bots. Lichess offers a [board API](https://lichess.org/blog/XlRW5REAAB8AUJJ-/welcome-lichess-boards) that I believe should let us challenge a bot account hosted on their site. This'll probably require some refactoring, but I think I'll be able to get it to work.

**Describe alternatives you've considered** :star2:
Blackmail my friends into playing with me. At two in the morning. On a weekday. 😈 

**Additional context** :memo:
♟️ - 🧑‍🦱 + 🤖   = ❤️ ?

**Comment by fave77** [comment]
@JadeMaveric I have plans for integrating stockfish on pbchess, it would allow for far more features than merely playing against bot, like analysis, insights in a far more cohesive manner. Implementing that will take time, currently I am focussing on making the groundwork, refactoring the current codebase and so as to make it extensible.

**Comment by JadeMaveric** [comment]
@fave77 Sweet! Looking forward to it. All the best
