### ISSUE TITLE
Include a link to the /register page from the login card

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#6]
**Is your feature request related to a problem? Please describe.** :bulb:
Not necessarily, but it does increase user experience.

**Describe the solution you'd like** :sparkles:
Modify the login card to include a link to the /register page like so:
![image](https://drive.google.com/uc?export=view&id=1nVKK988ZKHckPbv2gnYhWSemM0vK5_b-)

**Describe alternatives you've considered** :star2:
NA

**Additional context** :memo:
It would be more apt if we can get rid of the register link from the header since this is a one-time procedure. So, there should be only a Login link (due to frequent access) via which a new user can access the /register page.

**Comment by urvi-k** [comment]
@fave77 Can you assign me this issue?

**Comment by fave77** [comment]
Sure! If you face any hurdles, do reach out.

**Comment by fave77** [comment]
@cp-urvi-k Can you please share the update?

**Comment by shreetama123** [comment]
I would like to contribute in this as a part of jwoc

**Comment by Subhra264** [comment]
Hello! I want to work on this issue under JWOC
