### ISSUE TITLE
Multiple users can login with the same email

### ISSUE THREAD

**Issue by Coder-Srinivas** [fave77/pbchess#61]
**Describe the bug** :bug:
A user with the same email can register using a different username.

**To Reproduce** :mag:
Use a different username while registering. A new user is formed with the same email.

**Comment by Apprentice76** [comment]
Can I try my hand at this? I'm a gssoc '21 participant.

**Comment by adi-g15** [comment]
> 
> 
> Can I try my hand at this? I'm a gssoc '21 participant.

@Apprentice76 this issue was assigned already, and now has PR #62 too so it can't be assigned to you. You can look up some issue you find when on the website of this project 🙂

**Comment by Apprentice76** [comment]
My bad I thought it was a mentor-opened issue.
