### ISSUE TITLE
adding contributors profile image with Github handle in readme 

### ISSUE THREAD

**Issue by rajeshpanjiyar** [fave77/pbchess#63]
I want to add the **contributor's** section in the readme file. It is one of the best parts of every readme.
- I am a *participant* in **GSSoC'21**
- I would like to be assigned and start working.

**Comment by fave77** [comment]
@rajeshpanjiyar please go through this [issue's](https://github.com/fave77/pbchess/issues/47) thread

**Comment by adi-g15** [comment]
> 
> 
> I want to add the **contributor's** section in the readme file. It is one of the best parts of every readme.
> 
>     * I am a _participant_ in **GSSoC'21**
> 
>     * I would like to be assigned and start working.

@rajeshpanjiyar  Also please search for existing issues before creating a new one. This is the 3rd time it's been created here #47 #56.

**Comment by rajeshpanjiyar** [comment]
Sorry, it's my bad.

**Comment by adi-g15** [comment]
> 
> 
> Sorry, it's my bad.

@rajeshpanjiyar Getting away from it on Github is harder though 😂

https://github.com/search?q=is%3Aissue+author%3Arajeshpanjiyar+updated%3A%3E2021-03-07

**Comment by rajeshpanjiyar** [comment]
> > Sorry, it's my bad.
> 
> @rajeshpanjiyar Getting away from it on Github is harder though 😂
> 

@adi-g15 It's okay this project doesn't need to show contributors in the readme but generating an issue or say the same issue in all repo should not affect one. I generated the same issue in any project because I thought may they need such an update. I think you should go through this before trolling beginners
![image](https://user-images.githubusercontent.com/78999467/111595862-abdba280-87f4-11eb-95df-9620eea798ed.png)
 And I am glad some projects accepted the issue.
