### ISSUE TITLE
Implementing Change Password

### ISSUE THREAD

**Issue by Coder-Srinivas** [fave77/pbchess#66]
**Is your feature request related to a problem? Please describe.** :bulb:
The user currently has no way to change his/her password. 

**Describe the solution you'd like** :sparkles:
I would build a component inside the drop down menu providing the user to change his/her password. The request would be sent to the client over a new route. The server then sends the user an email to change his/her password.

**Comment by fave77** [comment]
@Coder-Srinivas no need to send any email, implement the change password feature using a form inside the `password` component.

The input fields would include `old password`, `new password`, and `confirm password`

The old password should match the existing hash and salt stored on the db, then only update the password
You can implement checks on the client side whether `new password` or `confirm password` are same or not

urlendpoint - `/update-pswd` (PUT request)
user.controller method - `updatePassword`
