### ISSUE TITLE
Scroll to top of the page button

### ISSUE THREAD

**Issue by DEEPIKA-SUK** [fave77/pbchess#68]
**Is your feature request related to a problem? Please describe.** :bulb:
Scroll to top of the page button is not present in "Learn" page.

**Describe the solution you'd like** :sparkles:
I would like to add this and want to contribute as a part of GSSOC 2021. 

**Describe alternatives you've considered** :star2:

**Additional context** :memo:

Kindly assign me this issue.

**Comment by DEEPIKA-SUK** [comment]
@fave77 Please assign me this issue as a part of GSSOC 2021.

**Comment by fave77** [comment]
@DEEPIKA-SUK implement this feature inside the vocab component 👍🏻

**Comment by DEEPIKA-SUK** [comment]
Kindly review my PR.

**Comment by DEEPIKA-SUK** [comment]
@fave77 Kindly review my PR.
