### ISSUE TITLE
Fix unit test for rendering component

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#7]
**Describe the bug** :bug:
Currently, `Navbar`, `Profile`, `Lobby`, and `PrivateRoute` components are throwing error for the unit test - **renders without crashing**!

**To Reproduce** :mag:
1. Go to `/client/src/test/App.test.js`
2. Uncomment the commented lines
3. Run `npm test` inside the **client** folder
4. Check the error message

**Expected behavior** :honeybee:
To pass the test for all the components.

**Screenshots** :camera:
![code](https://drive.google.com/uc?export=view&id=1UMkVmqFv4oCD5OMUzbshKgjMhZV_YOga)

**Desktop (please complete the following information):** :computer:
 - OS: [e.g. ubuntu]
 - Node.js [version - 12.18.3]

**Smartphone (please complete the following information):** :iphone:
NA

**Additional context** :memo:
NA

**Comment by Subhra264** [comment]
Hello!
Want to work on it 🙂🙂...
