### ISSUE TITLE
Revamp Learn Page

### ISSUE THREAD

**Issue by RahulBansal0502** [fave77/pbchess#73]
The learn Page is so static. Also, UI is not looking so good. I want to change the UI of learn page. Please assign this issue to me.

**Comment by fave77** [comment]
@RahulBansal0502 please provide a design mockup first as to how you wanna improve it

**Comment by RahulBansal0502** [comment]
![image](https://user-images.githubusercontent.com/56486309/111901414-193e3c00-8a5e-11eb-9cb3-2e1234464543.png)

I want to make this page like this. Means using the card and on hovering them they pop up. There are also two ways one is this in the above image and another is that on card only name is written like Adjournment, Algebraic and when player hover over them the card flips and information is written on it.

**Comment by RahulBansal0502** [comment]
Please assign this issue to me. I am a GSSOC participant.

**Comment by fave77** [comment]
@RahulBansal0502 This is not necessary, please suggest other alternatives.

**Comment by RahulBansal0502** [comment]
Instead of simple cards if we use glass cards and in background we use any vector image related to chess than it's look nice in my views.

**Comment by fave77** [comment]
@RahulBansal0502 Now that's a great suggestion! Please share your discord username...

**Comment by RahulBansal0502** [comment]
Rahul Bansal#8595

**Comment by fave77** [comment]
@RahulBansal0502 please include your changes only inside `Vocab` component and not `Learn` component

**Comment by fave77** [comment]
@RahulBansal0502 please provide your update on the progress

**Comment by vismitap** [comment]
May I try this issue as a part of GSSOC'21?

**Comment by fave77** [comment]
@vismitap can you share your discord username?

**Comment by vismitap** [comment]
> @vismitap can you share your discord username?

visp#8877

**Comment by fave77** [comment]
@vismitap please share your update...

**Comment by vismitap** [comment]
> @vismitap please share your update...

Working on it. Will complete it by today! 👍

**Comment by apurv-1** [comment]
@vismitap any update? It's been 4 days. Let us know if you're stuck?

**Comment by vismitap** [comment]
> @vismitap any update? It's been 4 days. Let us know if you're stuck?

I am so sorry! I tried changing the CSS but it did not look good. Glassmorphism did not look the way it should in learn page. So rolled back all the changes. I was busy with the college assignments and project so could not complete the issue. Still trying to make it look good! 😓 Please let me try for 1 more day and if I don't complete, unassign me.

**Comment by apurv-1** [comment]
> > @vismitap any update? It's been 4 days. Let us know if you're stuck?
> 
> I am so sorry! I tried changing the CSS but it did not look good. Glassmorphism did not look the way it should in learn page. So rolled back all the changes. I was busy with the college assignments and project so could not complete the issue. Still trying to make it look good! 😓 Please let me try for 1 more day and if I don't complete, unassign me.

No issues! I thought if you were stuck. Please take your time. 😀

**Comment by fave77** [comment]
> > @vismitap any update? It's been 4 days. Let us know if you're stuck?
> 
> I am so sorry! I tried changing the CSS but it did not look good. Glassmorphism did not look the way it should in learn page. So rolled back all the changes. I was busy with the college assignments and project so could not complete the issue. Still trying to make it look good! 😓 Please let me try for 1 more day and if I don't complete, unassign me.

@vismitap update?

**Comment by vismitap** [comment]
> > > @vismitap any update? It's been 4 days. Let us know if you're stuck?
> > 
> > 
> > I am so sorry! I tried changing the CSS but it did not look good. Glassmorphism did not look the way it should in learn page. So rolled back all the changes. I was busy with the college assignments and project so could not complete the issue. Still trying to make it look good! 😓 Please let me try for 1 more day and if I don't complete, unassign me.
> 
> @vismitap update?

Hey so sorry to keep you guys waiting!🙁 I am really caught up with all assignments, projects and internship. I am unassigning myself on this and will claim some other issue soon in future!
