### ISSUE TITLE
Learn section has letter tabs without terms

### ISSUE THREAD

**Issue by aanchal-fatwani** [fave77/pbchess#74]
ISSUE DETAILS
Currently, the learn section has some alphabet tabs that are clickable but do not redirect to the terms with that alphabet, as there are no terms starting with that letter.
This hampers user experience as the user might think of it as a flaw wherein the alphabet is not directing to the terms. 
Also, the code structure has been created by statically defining and creating links for all the alphabets.
 
The alphabets should only be present for which the terms exist in vocabulary.
The code structure can be improved by creating the links dynamically (rather than static typing) on the basis of the terms for better code quality and readability.

**Comment by aanchal-fatwani** [comment]
Hey @fave77, I am a GSSOC 2021 participant. I would like to work on the issue. 
Could you please update the issue with relevant tags and assign the same?

**Comment by fave77** [comment]
> The code structure can be improved by creating the links dynamically (rather than static typing)

@aanchal-fatwani Can you elaborate on this? How you're gonna do that? Also, please share your discord username!

**Comment by aanchal-fatwani** [comment]
@fave77 
For creating the links, we can improve upon the current structure to incorporate some looping mechanism based on the previously filtered result (alphabets that actually have terms corresponding to them) rather than statically typing them for all the alphabets(<a href="#A">A</a>-<a href="#B">B</a>- ...)  

My discord username is Aanchal#1668

**Comment by fave77** [comment]
@aanchal-fatwani please provide your update on the progress
