### ISSUE TITLE
Provide unit tests for keys.config.js

### ISSUE THREAD

**Issue by fave77** [fave77/pbchess#8]
**Is your feature request related to a problem? Please describe.** :bulb:
This is related to unit testing for the file `keys.config.js`.

**Describe the solution you'd like** :sparkles:
- Create a file inside `server/test/` named as **keys.config.spec.js** for one of the config files inside `server/src/configs/`.
- Make unit tests in jest for the function **genKeyPair** 

**Describe alternatives you've considered** :star2:
NA

**Additional context** :memo:
NA

**Comment by Subhra264** [comment]
Hello, I want to work on this issue under JWOC

**Comment by fave77** [comment]
@Subhra264 make sure the coverage is 100% for `keys.service.js` and create a file named  `keys.service.spec.js` inside the **test/services** folder.

NOTE: Since the issue was created, `keys.service.js` has been moved from `configs` to `services`.
