### ISSUE TITLE
Video player extends out of visible area 

### ISSUE THREAD

**Issue by aanchal-fatwani** [fave77/pbchess#83]
ISSUE DETAILS
Currently, the video player extends the scope of the visible area which makes it difficult to see the entire board in one go. 
Also, the player overlaps the vocabulary section on some small screen sizes.

We can display the player with a size corresponding to the screen sizes.

Hey @fave77, I am a GSSOC 2021 participant. I would like to work on the issue. 
Could you please update the issue with relevant tags and assign the same (Aanchal#1668)?

**Comment by fave77** [comment]
@aanchal-fatwani Please provide screenshots while reporting bugs relating to UI. Having said that, my plan for **/learn** page is to render the following components - `vocab`, `videos`, `lessons` and `puzzles` by implementing [tabs](https://react-bootstrap.github.io/components/tabs/).

NOTE: The `lessons` and `puzzles` component are not yet implemented.

Considering your claimed bug regarding UI is true, then why not use React Bootstrap Tabs for vocab and videos for now, and later when the other two components are done, we can easily extend it with few lines of code inside **/learn** page

**Comment by fave77** [comment]
The tabs should solve the overlap issue, and as for overflowing on smaller form factor, you can make the videos component responsive accordingly.

Provide screenshots for the issue, will assign it to you then 👍🏻

**Comment by aanchal-fatwani** [comment]
@fave77 Please find the screenshots of the issue and the proposed solution.
 
The video player had to be scrolled to check the entire game as the player extends the scope of the visible area.  
![Problem1](https://user-images.githubusercontent.com/63228776/113131852-5911da00-923b-11eb-8f82-911486e19b1b.PNG)

The player is overlapping the vocabulary section. 
![Problem2](https://user-images.githubusercontent.com/63228776/113131878-60d17e80-923b-11eb-9f29-4a99e99968d6.PNG)

Proposed solution:
![ProposedStyle1](https://user-images.githubusercontent.com/63228776/113132965-ca05c180-923c-11eb-99e6-ea1644efd479.PNG)

![ProposedStyle2](https://user-images.githubusercontent.com/63228776/113132975-cd00b200-923c-11eb-8253-7e7e2522c6e9.PNG)

**Comment by sahildotexe** [comment]
Hey , I'm a GSSOC participant and I'm well acquainted with HTML,CS,JS and React. I would love to collaborate with @aanchal-fatwani on this issue.
