### ISSUE TITLE
Adding Placeholder in login and register form

### ISSUE THREAD

**Issue by n-coder2k** [fave77/pbchess#88]
I would like to add placeholder in login form.
I am gssoc participant please assign me this issue.

**Comment by fave77** [comment]
@n-coder2k please also add placeholder on register form as well

**Comment by n-coder2k** [comment]
@fave77 I am not able to find html file for login and registration form. I am new to opensource ,please help me to get that html file.

**Comment by fave77** [comment]
> @fave77 I am not able to find html file for login and registration form. I am new to opensource ,please help me to get that html file.

@n-coder2k The frontend code for this project is available inside `client` folder and we are using React for the UI. So, you won't find any .html files, except every UI components, be it header or footer, are written using JSX.

Do note that tech stack was clearly mentioned in the readme. Hence, if you're completely new to React, just get a basic understanding of the syntax (especially JSX part).

As for your query, you will find code related to `login` & `register` inside `client/src/components` folder.

**Comment by n-coder2k** [comment]
@fave77  I am completely new to React , I wont be able to do this.

**Comment by JOEMN96** [comment]
assign this issue to me !

**Comment by fave77** [comment]
> assign this issue to me !

Are you a GSSoC'21 participant? If yes, then provide your discord username.

**Comment by guruc-134** [comment]
@fave77 i want to work on this issue;
 my discord user name is : GuruCharan(P)#3851

**Comment by fave77** [comment]
> @fave77 i want to work on this issue;
> my discord user name is : GuruCharan(P)#3851

Okay

**Comment by apurv-1** [comment]
@guruc-134 any update on this? Please feel free to reach out to us, if you face any issue.

**Comment by apurv-1** [comment]
Also @fave77, We already have labels above input fields. Having labels and placeholder both will be a little messy.
![Capture](https://user-images.githubusercontent.com/53378650/114210148-0c39ac00-997d-11eb-95cb-b768e3b9fa32.PNG)

**Comment by guruc-134** [comment]
@apurv-1  working on it,  sure I will reach out to you; have been caught up with assignment deadlines;
By the way, after reading your message from above; I got a doubt is this issue still valid?

**Comment by fave77** [comment]
@guruc-134 instead of providing labels you can have something like: `e.g. johndoe` and `e.g. Abcd1#@&` acting as placeholders for username and password.

**Comment by fave77** [comment]
@guruc-134 this issue should hardly take 10 mins.... please make the PR by today

**Comment by guruc-134** [comment]
extremely sorry for the delay , have been caught up in many works { college , clubs }
thats the reason i couldnt update you with your work.

**Comment by MennaMagdy2019** [comment]
Can I work on this issue, please? @fave77

**Comment by devRawnie** [comment]
I have created a pull request after adding the placeholders for Login and Register components.
Kindly assign me this issue and check the pull request for the same.

**Comment by fave77** [comment]
> I have created a pull request after adding the placeholders for Login and Register components.
> Kindly assign me this issue and check the pull request for the same.

@devRawnie please share your discord username if you are a GSSoC'21 participant

**Comment by devRawnie** [comment]
Yes, I am a GSSOC'21 participant. My discord username is srohit#6275
