### ISSUE TITLE
Console logs exposing tokens on client.

### ISSUE THREAD

**Issue by apurv-1** [fave77/pbchess#91]
## Issue(s)
There quite a few console logs exposing tokens from the Client on Production.

## Screenshots
![1024](https://user-images.githubusercontent.com/53378650/113863349-2d589c00-97c7-11eb-8302-5b16cff7aa5e.PNG)

## ToDo
Remove all the console logs from the Client.

**Comment by sourabhkumar45** [comment]
I would like work on this issue.

**Comment by fave77** [comment]
@sourabhkumar45 please provide your gssoc21 discord username

**Comment by sourabhkumar45** [comment]
> @sourabhkumar45 please provide your gssoc21 discord username

Sourabh(P)#6334
