### ISSUE TITLE
Bug in Reset Password

### ISSUE THREAD

**Issue by ShrutiOmer** [fave77/pbchess#97]
**Describe the bug** :bug:
When user go for Forget Password, a window opens to Reset Password and if user didn't enter any email and click the Submit button. A window opens saying "Please wait while we send you the email", so instead of this "This field is required" message must be displayed.

**To Reproduce** :mag:
1. Go to 'Play'
2. Click on 'Forgot password'
3. Click on 'Submit'
4. See message "Please wait...."

**Screenshots** :camera:

![image](https://user-images.githubusercontent.com/75009990/114265975-5e2c1180-9a11-11eb-8ca3-d0cb271b75c1.png)

After clicking on submit without entering email.
![image](https://user-images.githubusercontent.com/75009990/114266005-81ef5780-9a11-11eb-9464-608b8c3e3536.png)

**Comment by ShrutiOmer** [comment]
Please assign this issue to me , I am a GSSOC participant.

**Comment by fave77** [comment]
@ShrutiOmer please share your discord username

**Comment by ShrutiOmer** [comment]
Yes, 
Discord user name: shruti(P) 
Discord user tag: #1880
