### ISSUE TITLE
Navigation Bar Don't Collapse in Mobile Biew

### ISSUE THREAD

**Issue by kumar-tushar** [fave77/pbchess#98]
**Describe the bug** :bug:
When you navigate to another webpage, then navigation Bar don't collapse in Mobile View.

**To Reproduce** :mag:
1. Go to 'mobile view'
2. Click on 'learn'
3. Scroll down to 'bottom'
6. See an error

**Expected behavior** :honeybee:
The Navigation bar has to collapse after clicking on the nav link.

![Screenshot_2021-04-10-21-44-00-898_com android chrome](https://user-images.githubusercontent.com/56949668/114277026-06100200-9a47-11eb-8a75-012703ba57ba.jpg)

**Smartphone (please complete the following information):** :iphone:

**Comment by kumar-tushar** [comment]
@fave77 Excited to collaborate on this project!

**Comment by fave77** [comment]
@kumar-tushar Are you a GSSoC'21 participant? If yes, then please share your discord username!

**Comment by kumar-tushar** [comment]
@fave77  Discord Username: Tushar Kumar Verma#2210

**Comment by kumar-tushar** [comment]
@fave77  Sir, I think it is a level 3 issue because it took a lot of time to remove this bug.

#117 closes this issue

**Comment by kumar-tushar** [comment]
> @fave77 Sir, I think it is a level 3 issue because it took a lot of time to remove this bug.
> 
> #117 closes this issue

@fave77
