### ISSUE TITLE
Align Content "Self-Center" of Vocabulary Section 

### ISSUE THREAD

**Issue by kumar-tushar** [fave77/pbchess#99]
**Is your feature request related to a problem? Please describe.** :bulb:
The Playing rules content is not "self-aligned"

**Describe the solution you'd like** :sparkles:
I want to use the CSS class "align: self-center"

# BEFORE
![Screenshot (333)](https://user-images.githubusercontent.com/56949668/114277314-4fad1c80-9a48-11eb-8073-a134e5812764.png)

# AFTER Self-Center
![Screenshot (332)](https://user-images.githubusercontent.com/56949668/114277329-59368480-9a48-11eb-87b7-7bfeefc48e7d.png)

IGNORE GREY COLOR!!!

**Comment by kumar-tushar** [comment]
@fave77 Excited to collaborate on this project!

**Comment by rijusougata13** [comment]
can i work on this?

**Comment by kumar-tushar** [comment]
@rijusougata13 It is already assigned

**Comment by kumar-tushar** [comment]
> can i work on this?
@rijusougata13 It is already assigned
